name: Weather App Workflow

on:
  pull_request:
    branches:
      - weather-app

jobs:
  init-ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
      - name: Install dependencies
        run: npm clear-install --no-audit
      - name: Run lint
        run: npm run lint:weather
      - name: Run build script
        run: npm run build:weather
